postgres:
  host: "${POSTGRES_HOST:127.0.0.1}"
  port: "${POSTGRES_PORT:5433}"
  database: "${POSTGRES_DB:crediyapplications}"
  username: "${POSTGRES_USER:hdj}"
  password: "${POSTGRES_PASSWORD:salsam2323}"
server:
  port: 8081
  error:
    include-message: "always"
spring:
  application:
    name: "applicationservices"
  devtools:
    add-properties: false
  r2dbc:
    url: "r2dbc:postgresql://127.0.0.1:5433/crediyapplications"
    username: "hdj"
    password: "salsam2323"
    pool:
      enabled: true
      initial-size: 2
      max-size: 20
      max-idle-time: "30m"
      validation-query: "SELECT 1"
  sql:
    init:
      mode: "never"

management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
