spring:
  application:
    name: "applicationservices"
  devtools:
    add-properties: false
  r2dbc:
    url: "r2dbc:postgresql://${POSTGRES_HOST:127.0.0.1}:${POSTGRES_PORT:5433}/${POSTGRES_DB:crediyapps}"
    username: "${POSTGRES_USER:hdj}"
    password: "${POSTGRES_PASSWORD:salsam2323}"
    pool:
      enabled: true
      initial-size: 2
      max-size: 20
      max-idle-time: "30m"
      validation-query: "SELECT 1"
  sql:
    init:
      mode: "always"
      schema-locations: "classpath:schema.sql"

postgres:
  host: "${POSTGRES_HOST:127.0.0.1}"
  port: "${POSTGRES_PORT:5433}"
  database: "${POSTGRES_DB:crediyapps}"
  schema: "public"
  username: "${POSTGRES_USER:hdj}"
  password: "${POSTGRES_PASSWORD:salsam2323}"

server:
  port: "${PORT}"
  error:
    include-message: "always"

management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
  health:
    circuitbreakers:
      enabled: true

cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

logging:
  level:
    org.springframework.r2dbc: "DEBUG"
    bootcamp.reto.powerup.r2dbc: "DEBUG"
    org.springframework.web.reactive: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

adapter:
  restconsumer:
    timeout: 5000
    url: "http://localhost:8080"
  sqs:
    region: "${AWS_REGION:us-east-1}"
    queueUrl: "${AWS_SQS_QUEUE_URL:https://sqs.us-east-1.amazonaws.com/880370050201/cola_cambio_estado_solicitud}"
    queue-capacity-url: "${AWS_SQS_QUEUE_CAPACITY_URL:https://sqs.us-east-1.amazonaws.com/880370050201/cola_capacidad_de_endeudamiento}"
    queue-report: "${AWS_SQS_QUEUE_REPORTS}"
    credentials:
      access-key: "${AWS_ACCESS_KEY_ID}"
      secret-key: "${AWS_SECRET_ACCESS_KEY}"

jwt:
  secret-key: "$mySecretKeyForJWT2024VeryLongAndSecureKey123456789"
  expiration: 3600000

entrypoint:
  sqs:
    region: "${REGION:us-east-1}"
    endpoint: "${AWS_ENDPOINT:https://sqs.us-east-1.amazonaws.com/880370050201}"
    queueUrl: "${AWS_QUEUE_URL_UPDATE:respuesta_actualiza_credit_request}"
    waitTimeSeconds: 20
    maxNumberOfMessages: 10
    visibilityTimeoutSeconds: 10
    numberOfThreads: 1
